### PR TITLE
Adding api and worker containers

### PR DESCRIPTION
**Pull request by mkam**

### CODE REVIEW

**Comment by pglass** [comment]
:snail:

**Comment by pglass** [comment]
:fish:

**Comment by pglass** [comment]
:tropical_fish:

**Comment by pglass** [comment]
Yeah, this worked for me. 

(Unrelated: There was a `TypeError: execute_job() takes exactly 2 arguments (1 given)` exception in the worker when I tried to run a job though...)

**Comment by jmvrbanac** [comment]
Looks good. Just as a side note, those scripts were really handy before the advent of docker compose. You might look into using that so you don't have to maintain two scripts for running and building.

**Pull request merged**
